"""add_timestamps

Revision ID: 17598402bebe
Revises: c86b75ceb6b3
Create Date: 2026-04-20 15:48:36.423885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17598402bebe'
down_revision: Union[str, Sequence[str], None] = 'c86b75ceb6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in ('offer', 'order', 'partner', 'user'):
        op.add_column(
            table_name,
            sa.Column(
                'created_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('now()'),
                nullable=False,
            ),
        )
        op.add_column(
            table_name,
            sa.Column(
                'updated_at',
                sa.DateTime(timezone=True),
                server_default=sa.text('now()'),
                nullable=False,
            ),
        )
        op.alter_column(table_name, 'created_at', server_default=None)
        op.alter_column(table_name, 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('partner', 'updated_at')
    op.drop_column('partner', 'created_at')
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'created_at')
    op.drop_column('offer', 'updated_at')
    op.drop_column('offer', 'created_at')
    # ### end Alembic commands ###
