"""Add description and pickup_time to Offer

Revision ID: 707604fea493
Revises: d4f4a7b9c2e3
Create Date: 2026-04-27 13:12:11.569867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '707604fea493'
down_revision: Union[str, Sequence[str], None] = 'd4f4a7b9c2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), server_default="", nullable=False))
    op.add_column('offer', sa.Column('pickup_time', sqlmodel.sql.sqltypes.AutoString(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'pickup_time')
    op.drop_column('offer', 'description')
    # ### end Alembic commands ###
