"""add_code_rating_fields

Revision ID: b31ceb7f4383
Revises: 17598402bebe
Create Date: 2026-04-21 22:24:06.494309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31ceb7f4383'
down_revision: Union[str, Sequence[str], None] = '17598402bebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.add_column('order', sa.Column('code', sa.String(length=4), server_default='', nullable=False))
    op.alter_column('order', 'code', server_default=None)
    op.add_column('partner', sa.Column('description', sa.String(), server_default='', nullable=False))
    op.alter_column('partner', 'description', server_default=None)
    op.add_column('partner', sa.Column('category', sa.String(), server_default='', nullable=False))
    op.alter_column('partner', 'category', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner', 'category')
    op.drop_column('partner', 'description')
    op.drop_column('order', 'code')
    op.drop_table('rating')
    # ### end Alembic commands ###
